import type { TeamMember } from '@/types/team';

export interface TeamTemplate {
    id: string;
    name: string;
    description: string;
    format: 'Singles' | 'Doubles' | 'VGC';
    playstyle: string;
    pokemon: Partial<TeamMember>[];
    strategy: string;
    strengths: string[];
    weaknesses: string[];
}

export const TEAM_TEMPLATES: TeamTemplate[] = [
    {
        id: 'hyper-offense',
        name: 'Hyper Offense',
        description: 'Fast, hard-hitting sweepers that overwhelm opponents with speed and power',
        format: 'Singles',
        playstyle: 'Offensive',
        strategy: 'Lead with a fast setup sweeper, use priority moves to clean up weakened opponents, and maintain offensive pressure throughout the battle.',
        strengths: ['High damage output', 'Fast-paced games', 'Momentum control'],
        weaknesses: ['Vulnerable to priority', 'Struggles against walls', 'Requires prediction'],
        pokemon: [
            {
                name: 'Dragapult',
                types: ['dragon', 'ghost'],
                ability: 'Infiltrator',
                nature: 'Jolly',
                item: 'Choice Band',
                moves: ['Dragon Darts', 'U-turn', 'Phantom Force', 'Sucker Punch'],
                evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
            },
            {
                name: 'Garchomp',
                types: ['dragon', 'ground'],
                ability: 'Rough Skin',
                nature: 'Jolly',
                item: 'Life Orb',
                moves: ['Earthquake', 'Outrage', 'Stone Edge', 'Swords Dance'],
                evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
            },
            {
                name: 'Weavile',
                types: ['dark', 'ice'],
                ability: 'Pressure',
                nature: 'Jolly',
                item: 'Choice Scarf',
                moves: ['Triple Axel', 'Knock Off', 'Ice Shard', 'Low Kick'],
                evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
            },
            {
                name: 'Volcarona',
                types: ['bug', 'fire'],
                ability: 'Flame Body',
                nature: 'Timid',
                item: 'Heavy-Duty Boots',
                moves: ['Quiver Dance', 'Flamethrower', 'Bug Buzz', 'Giga Drain'],
                evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
            },
            {
                name: 'Azumarill',
                types: ['water', 'fairy'],
                ability: 'Huge Power',
                nature: 'Adamant',
                item: 'Sitrus Berry',
                moves: ['Aqua Jet', 'Play Rough', 'Liquidation', 'Belly Drum'],
                evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Rillaboom',
                types: ['grass'],
                ability: 'Grassy Surge',
                nature: 'Adamant',
                item: 'Choice Band',
                moves: ['Grassy Glide', 'Wood Hammer', 'U-turn', 'Knock Off'],
                evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
            },
        ],
    },
    {
        id: 'rain-team',
        name: 'Rain Dance',
        description: 'Weather-based team that abuses rain to boost Water moves and speed',
        format: 'Singles',
        playstyle: 'Weather',
        strategy: 'Set up rain with Pelipper, then sweep with Swift Swim users. Use Thunder for perfect accuracy and boosted Water moves.',
        strengths: ['Boosted Water moves', 'Swift Swim speed', 'Thunder accuracy'],
        weaknesses: ['Weather wars', 'Electric weakness', 'Setup dependent'],
        pokemon: [
            {
                name: 'Pelipper',
                types: ['water', 'flying'],
                ability: 'Drizzle',
                nature: 'Bold',
                item: 'Damp Rock',
                moves: ['Scald', 'Hurricane', 'U-turn', 'Roost'],
                evs: { hp: 248, atk: 0, def: 252, spa: 0, spd: 8, spe: 0 },
            },
            {
                name: 'Barraskewda',
                types: ['water'],
                ability: 'Swift Swim',
                nature: 'Adamant',
                item: 'Life Orb',
                moves: ['Liquidation', 'Close Combat', 'Crunch', 'Flip Turn'],
                evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
            },
            {
                name: 'Kingdra',
                types: ['water', 'dragon'],
                ability: 'Swift Swim',
                nature: 'Modest',
                item: 'Life Orb',
                moves: ['Hydro Pump', 'Draco Meteor', 'Ice Beam', 'Hurricane'],
                evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
            },
            {
                name: 'Ferrothorn',
                types: ['grass', 'steel'],
                ability: 'Iron Barbs',
                nature: 'Relaxed',
                item: 'Leftovers',
                moves: ['Power Whip', 'Gyro Ball', 'Leech Seed', 'Stealth Rock'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Zapdos',
                types: ['electric', 'flying'],
                ability: 'Static',
                nature: 'Timid',
                item: 'Heavy-Duty Boots',
                moves: ['Thunder', 'Hurricane', 'Heat Wave', 'Roost'],
                evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
            },
            {
                name: 'Toxapex',
                types: ['poison', 'water'],
                ability: 'Regenerator',
                nature: 'Bold',
                item: 'Black Sludge',
                moves: ['Scald', 'Recover', 'Haze', 'Toxic Spikes'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
        ],
    },
    {
        id: 'balanced-core',
        name: 'Balanced Core',
        description: 'Well-rounded team with offensive and defensive options',
        format: 'Singles',
        playstyle: 'Balanced',
        strategy: 'Adapt to opponent\'s team composition. Use defensive cores to wall threats and offensive Pokemon to apply pressure.',
        strengths: ['Versatile', 'Good type coverage', 'Handles most threats'],
        weaknesses: ['Jack of all trades', 'Can be outpaced', 'Requires skill'],
        pokemon: [
            {
                name: 'Landorus-Therian',
                types: ['ground', 'flying'],
                ability: 'Intimidate',
                nature: 'Jolly',
                item: 'Choice Scarf',
                moves: ['Earthquake', 'U-turn', 'Stone Edge', 'Stealth Rock'],
                evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
            },
            {
                name: 'Toxapex',
                types: ['poison', 'water'],
                ability: 'Regenerator',
                nature: 'Bold',
                item: 'Black Sludge',
                moves: ['Scald', 'Recover', 'Haze', 'Toxic'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Heatran',
                types: ['fire', 'steel'],
                ability: 'Flash Fire',
                nature: 'Timid',
                item: 'Leftovers',
                moves: ['Magma Storm', 'Earth Power', 'Taunt', 'Stealth Rock'],
                evs: { hp: 252, atk: 0, def: 0, spa: 4, spd: 0, spe: 252 },
            },
            {
                name: 'Clefable',
                types: ['fairy'],
                ability: 'Magic Guard',
                nature: 'Bold',
                item: 'Life Orb',
                moves: ['Moonblast', 'Flamethrower', 'Soft-Boiled', 'Calm Mind'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Corviknight',
                types: ['flying', 'steel'],
                ability: 'Pressure',
                nature: 'Impish',
                item: 'Leftovers',
                moves: ['Brave Bird', 'Roost', 'Defog', 'U-turn'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Tapu Koko',
                types: ['electric', 'fairy'],
                ability: 'Electric Surge',
                nature: 'Timid',
                item: 'Choice Specs',
                moves: ['Thunderbolt', 'Dazzling Gleam', 'Volt Switch', 'Hidden Power Ice'],
                evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
            },
        ],
    },
    {
        id: 'trick-room',
        name: 'Trick Room',
        description: 'Reverse speed tier team that dominates under Trick Room',
        format: 'Doubles',
        playstyle: 'Trick Room',
        strategy: 'Set up Trick Room and sweep with slow, powerful Pokemon. Use Fake Out and redirection to protect your setters.',
        strengths: ['Reverses speed tiers', 'Powerful slow attackers', 'Disrupts fast teams'],
        weaknesses: ['Limited turns', 'Setup dependent', 'Vulnerable to Taunt'],
        pokemon: [
            {
                name: 'Dusclops',
                types: ['ghost'],
                ability: 'Frisk',
                nature: 'Relaxed',
                item: 'Eviolite',
                moves: ['Trick Room', 'Night Shade', 'Will-O-Wisp', 'Pain Split'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Torkoal',
                types: ['fire'],
                ability: 'Drought',
                nature: 'Quiet',
                item: 'Charcoal',
                moves: ['Eruption', 'Heat Wave', 'Solar Beam', 'Protect'],
                evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 },
            },
            {
                name: 'Rhyperior',
                types: ['ground', 'rock'],
                ability: 'Solid Rock',
                nature: 'Brave',
                item: 'Weakness Policy',
                moves: ['Rock Slide', 'High Horsepower', 'Ice Punch', 'Protect'],
                evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Conkeldurr',
                types: ['fighting'],
                ability: 'Guts',
                nature: 'Brave',
                item: 'Flame Orb',
                moves: ['Drain Punch', 'Mach Punch', 'Ice Punch', 'Protect'],
                evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Indeedee-F',
                types: ['psychic', 'normal'],
                ability: 'Psychic Surge',
                nature: 'Sassy',
                item: 'Safety Goggles',
                moves: ['Psychic', 'Follow Me', 'Helping Hand', 'Protect'],
                evs: { hp: 252, atk: 0, def: 0, spa: 4, spd: 252, spe: 0 },
            },
            {
                name: 'Stakataka',
                types: ['rock', 'steel'],
                ability: 'Beast Boost',
                nature: 'Brave',
                item: 'Shuca Berry',
                moves: ['Gyro Ball', 'Rock Slide', 'Body Press', 'Protect'],
                evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 },
            },
        ],
    },
    {
        id: 'sun-team',
        name: 'Sun Team',
        description: 'Solar power team that abuses harsh sunlight',
        format: 'Singles',
        playstyle: 'Weather',
        strategy: 'Set sun with Torkoal or Ninetales, then sweep with Chlorophyll users and boosted Fire moves.',
        strengths: ['Boosted Fire moves', 'Chlorophyll speed', 'Solar Beam instant'],
        weaknesses: ['Water weakness', 'Weather wars', 'Rock weakness'],
        pokemon: [
            {
                name: 'Ninetales',
                types: ['fire'],
                ability: 'Drought',
                nature: 'Timid',
                item: 'Heat Rock',
                moves: ['Flamethrower', 'Solar Beam', 'Will-O-Wisp', 'Nasty Plot'],
                evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
            },
            {
                name: 'Venusaur',
                types: ['grass', 'poison'],
                ability: 'Chlorophyll',
                nature: 'Modest',
                item: 'Life Orb',
                moves: ['Solar Beam', 'Sludge Bomb', 'Earth Power', 'Weather Ball'],
                evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
            },
            {
                name: 'Charizard',
                types: ['fire', 'flying'],
                ability: 'Solar Power',
                nature: 'Timid',
                item: 'Choice Specs',
                moves: ['Fire Blast', 'Solar Beam', 'Air Slash', 'Focus Blast'],
                evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
            },
            {
                name: 'Heatran',
                types: ['fire', 'steel'],
                ability: 'Flash Fire',
                nature: 'Timid',
                item: 'Leftovers',
                moves: ['Magma Storm', 'Solar Beam', 'Earth Power', 'Stealth Rock'],
                evs: { hp: 252, atk: 0, def: 0, spa: 4, spd: 0, spe: 252 },
            },
            {
                name: 'Lilligant',
                types: ['grass'],
                ability: 'Chlorophyll',
                nature: 'Timid',
                item: 'Life Orb',
                moves: ['Solar Beam', 'Sleep Powder', 'Quiver Dance', 'Hidden Power Fire'],
                evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
            },
            {
                name: 'Dugtrio',
                types: ['ground'],
                ability: 'Arena Trap',
                nature: 'Jolly',
                item: 'Focus Sash',
                moves: ['Earthquake', 'Stone Edge', 'Sucker Punch', 'Stealth Rock'],
                evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
            },
        ],
    },
    {
        id: 'stall-team',
        name: 'Stall Team',
        description: 'Defensive team focused on outlasting opponents with recovery and hazards',
        format: 'Singles',
        playstyle: 'Defensive',
        strategy: 'Set up hazards early, wear down opponents with passive damage, and use Regenerator cores to maintain health. Stall out opposing threats.',
        strengths: ['Excellent longevity', 'Hazard stacking', 'Hard to break through'],
        weaknesses: ['Slow games', 'Vulnerable to setup', 'Taunt weakness'],
        pokemon: [
            {
                name: 'Blissey',
                types: ['normal'],
                ability: 'Natural Cure',
                nature: 'Bold',
                item: 'Heavy-Duty Boots',
                moves: ['Seismic Toss', 'Soft-Boiled', 'Toxic', 'Stealth Rock'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Toxapex',
                types: ['poison', 'water'],
                ability: 'Regenerator',
                nature: 'Bold',
                item: 'Black Sludge',
                moves: ['Scald', 'Recover', 'Haze', 'Toxic Spikes'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Corviknight',
                types: ['flying', 'steel'],
                ability: 'Pressure',
                nature: 'Impish',
                item: 'Leftovers',
                moves: ['Brave Bird', 'Roost', 'Defog', 'Body Press'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Slowbro',
                types: ['water', 'psychic'],
                ability: 'Regenerator',
                nature: 'Bold',
                item: 'Heavy-Duty Boots',
                moves: ['Scald', 'Slack Off', 'Future Sight', 'Teleport'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Skarmory',
                types: ['steel', 'flying'],
                ability: 'Sturdy',
                nature: 'Impish',
                item: 'Rocky Helmet',
                moves: ['Spikes', 'Roost', 'Whirlwind', 'Brave Bird'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Alomomola',
                types: ['water'],
                ability: 'Regenerator',
                nature: 'Bold',
                item: 'Leftovers',
                moves: ['Scald', 'Wish', 'Protect', 'Flip Turn'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
        ],
    },
    {
        id: 'sand-team',
        name: 'Sandstorm',
        description: 'Weather team that uses sandstorm to boost Rock types and chip damage',
        format: 'Singles',
        playstyle: 'Weather',
        strategy: 'Set sandstorm with Tyranitar or Hippowdon, then use Sand Rush sweepers and boosted Rock-type special defense.',
        strengths: ['Passive chip damage', 'Rock SpD boost', 'Sand Rush speed'],
        weaknesses: ['Weather wars', 'Ground weakness', 'Limited type diversity'],
        pokemon: [
            {
                name: 'Tyranitar',
                types: ['rock', 'dark'],
                ability: 'Sand Stream',
                nature: 'Adamant',
                item: 'Smooth Rock',
                moves: ['Stone Edge', 'Crunch', 'Dragon Dance', 'Earthquake'],
                evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
            },
            {
                name: 'Excadrill',
                types: ['ground', 'steel'],
                ability: 'Sand Rush',
                nature: 'Jolly',
                item: 'Life Orb',
                moves: ['Earthquake', 'Iron Head', 'Rock Slide', 'Rapid Spin'],
                evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
            },
            {
                name: 'Garchomp',
                types: ['dragon', 'ground'],
                ability: 'Rough Skin',
                nature: 'Jolly',
                item: 'Rocky Helmet',
                moves: ['Earthquake', 'Stealth Rock', 'Swords Dance', 'Scale Shot'],
                evs: { hp: 252, atk: 200, def: 0, spa: 0, spd: 0, spe: 56 },
            },
            {
                name: 'Hippowdon',
                types: ['ground'],
                ability: 'Sand Stream',
                nature: 'Impish',
                item: 'Leftovers',
                moves: ['Earthquake', 'Slack Off', 'Stealth Rock', 'Whirlwind'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Gliscor',
                types: ['ground', 'flying'],
                ability: 'Poison Heal',
                nature: 'Impish',
                item: 'Toxic Orb',
                moves: ['Earthquake', 'Roost', 'Protect', 'Toxic'],
                evs: { hp: 252, atk: 0, def: 184, spa: 0, spd: 72, spe: 0 },
            },
            {
                name: 'Magnezone',
                types: ['electric', 'steel'],
                ability: 'Magnet Pull',
                nature: 'Modest',
                item: 'Choice Specs',
                moves: ['Thunderbolt', 'Flash Cannon', 'Volt Switch', 'Body Press'],
                evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 },
            },
        ],
    },
    {
        id: 'vgc-series13',
        name: 'VGC Series 13',
        description: 'Competitive VGC doubles team with restricted Pokemon',
        format: 'VGC',
        playstyle: 'Balanced',
        strategy: 'Use Tailwind for speed control, Fake Out for disruption, and powerful restricted Pokemon for damage. Protect key threats.',
        strengths: ['Speed control', 'Powerful restricted Pokemon', 'Good synergy'],
        weaknesses: ['Requires good positioning', 'Vulnerable to Trick Room', 'Weather dependent'],
        pokemon: [
            {
                name: 'Groudon',
                types: ['ground'],
                ability: 'Drought',
                nature: 'Adamant',
                item: 'Assault Vest',
                moves: ['Precipice Blades', 'Heat Crash', 'Rock Slide', 'Protect'],
                evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Calyrex-Shadow',
                types: ['psychic', 'ghost'],
                ability: 'As One',
                nature: 'Timid',
                item: 'Focus Sash',
                moves: ['Astral Barrage', 'Expanding Force', 'Protect', 'Nasty Plot'],
                evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
            },
            {
                name: 'Incineroar',
                types: ['fire', 'dark'],
                ability: 'Intimidate',
                nature: 'Careful',
                item: 'Sitrus Berry',
                moves: ['Fake Out', 'Flare Blitz', 'Parting Shot', 'Protect'],
                evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 252, spe: 0 },
            },
            {
                name: 'Rillaboom',
                types: ['grass'],
                ability: 'Grassy Surge',
                nature: 'Adamant',
                item: 'Assault Vest',
                moves: ['Grassy Glide', 'Wood Hammer', 'Fake Out', 'U-turn'],
                evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Tornadus',
                types: ['flying'],
                ability: 'Prankster',
                nature: 'Timid',
                item: 'Covert Cloak',
                moves: ['Tailwind', 'Bleakwind Storm', 'Taunt', 'Protect'],
                evs: { hp: 252, atk: 0, def: 0, spa: 4, spd: 0, spe: 252 },
            },
            {
                name: 'Amoonguss',
                types: ['grass', 'poison'],
                ability: 'Regenerator',
                nature: 'Calm',
                item: 'Sitrus Berry',
                moves: ['Spore', 'Rage Powder', 'Pollen Puff', 'Protect'],
                evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 252, spe: 4 },
            },
        ],
    },
    {
        id: 'monotype-steel',
        name: 'Monotype Steel',
        description: 'Steel-type monotype team with excellent defensive synergy',
        format: 'Singles',
        playstyle: 'Balanced',
        strategy: 'Use Steel-type resistances to wall most attacks. Set up with Swords Dance or Iron Defense, then sweep.',
        strengths: ['Excellent resistances', 'Strong defensive core', 'Good offensive options'],
        weaknesses: ['Fire weakness', 'Ground weakness', 'Fighting weakness'],
        pokemon: [
            {
                name: 'Melmetal',
                types: ['steel'],
                ability: 'Iron Fist',
                nature: 'Adamant',
                item: 'Assault Vest',
                moves: ['Double Iron Bash', 'Thunder Punch', 'Ice Punch', 'Earthquake'],
                evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Corviknight',
                types: ['flying', 'steel'],
                ability: 'Pressure',
                nature: 'Impish',
                item: 'Leftovers',
                moves: ['Brave Bird', 'Roost', 'Defog', 'Body Press'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Excadrill',
                types: ['ground', 'steel'],
                ability: 'Mold Breaker',
                nature: 'Jolly',
                item: 'Life Orb',
                moves: ['Earthquake', 'Iron Head', 'Rock Slide', 'Swords Dance'],
                evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
            },
            {
                name: 'Heatran',
                types: ['fire', 'steel'],
                ability: 'Flash Fire',
                nature: 'Timid',
                item: 'Air Balloon',
                moves: ['Magma Storm', 'Earth Power', 'Flash Cannon', 'Stealth Rock'],
                evs: { hp: 252, atk: 0, def: 0, spa: 4, spd: 0, spe: 252 },
            },
            {
                name: 'Ferrothorn',
                types: ['grass', 'steel'],
                ability: 'Iron Barbs',
                nature: 'Relaxed',
                item: 'Leftovers',
                moves: ['Power Whip', 'Gyro Ball', 'Leech Seed', 'Spikes'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Scizor',
                types: ['bug', 'steel'],
                ability: 'Technician',
                nature: 'Adamant',
                item: 'Choice Band',
                moves: ['Bullet Punch', 'U-turn', 'Superpower', 'Knock Off'],
                evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 },
            },
        ],
    },
    {
        id: 'baton-pass',
        name: 'Baton Pass Chain',
        description: 'Setup sweepers that pass boosts to each other',
        format: 'Singles',
        playstyle: 'Setup',
        strategy: 'Set up stat boosts with one Pokemon, then Baton Pass to another to continue boosting or sweep. Build momentum.',
        strengths: ['Snowballs quickly', 'Hard to stop once rolling', 'Versatile'],
        weaknesses: ['Vulnerable to Haze/Roar', 'Requires setup time', 'Prediction heavy'],
        pokemon: [
            {
                name: 'Ninjask',
                types: ['bug', 'flying'],
                ability: 'Speed Boost',
                nature: 'Jolly',
                item: 'Focus Sash',
                moves: ['Baton Pass', 'Protect', 'Substitute', 'Swords Dance'],
                evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 4, spe: 252 },
            },
            {
                name: 'Espeon',
                types: ['psychic'],
                ability: 'Magic Bounce',
                nature: 'Timid',
                item: 'Leftovers',
                moves: ['Baton Pass', 'Calm Mind', 'Substitute', 'Stored Power'],
                evs: { hp: 252, atk: 0, def: 0, spa: 4, spd: 0, spe: 252 },
            },
            {
                name: 'Scolipede',
                types: ['bug', 'poison'],
                ability: 'Speed Boost',
                nature: 'Jolly',
                item: 'Black Sludge',
                moves: ['Baton Pass', 'Protect', 'Swords Dance', 'Megahorn'],
                evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 4, spe: 252 },
            },
            {
                name: 'Mew',
                types: ['psychic'],
                ability: 'Synchronize',
                nature: 'Jolly',
                item: 'Leftovers',
                moves: ['Baton Pass', 'Rock Polish', 'Swords Dance', 'Taunt'],
                evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 4, spe: 252 },
            },
            {
                name: 'Vaporeon',
                types: ['water'],
                ability: 'Water Absorb',
                nature: 'Bold',
                item: 'Leftovers',
                moves: ['Baton Pass', 'Acid Armor', 'Substitute', 'Scald'],
                evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
            },
            {
                name: 'Blaziken',
                types: ['fire', 'fighting'],
                ability: 'Speed Boost',
                nature: 'Adamant',
                item: 'Life Orb',
                moves: ['Baton Pass', 'Swords Dance', 'Flare Blitz', 'Close Combat'],
                evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
            },
        ],
    },
];

